### PR TITLE
messageAddArguments: accept argument values with unbalanced quotes

### PR DESCRIPTION
**Pull request by monnerat**
There are a certain number of virussed e-mails that have malformed mime headers (unterminated quoted arguments), probably intentionally. This currently bypasses the checks on targetted files (there was even a TODO about it).

This PR considers an unbalanced quoted argument value to extend to the end of line, effectively allowing to check the target files.
It also prevents a pointer to advance after end of line.

Thanks for considering it.

### CODE REVIEW

**Comment by monnerat** [comment]
Ping ?
Is there anybody in there ?

**Comment by micah-at-talos** [comment]
Good morning monnerat.  Thanks for submitting the pull request.  

Sorry, we haven't had the chance to look at your pull request yet.  We're presently involved in release engineering for 0.99.4, and attempting to resolve a couple outstanding issues so we can get 0.100.0-rc out the door.  

We'll take a look at your submission when we are able.

**Comment by monnerat** [comment]
> We'll take a look at your submission when we are able.

Thanks in advance

**Comment by monnerat** [comment]
Commit 6c11e82 fixes it.
Thanks for applying.
Closing.

**Comment by micah-at-talos** [comment]
Apple Mail apparently thought updates from github regarding this particular PR were spam and I didn't notice it in my junk mailbox until now.

We apparently forgot to close the PR when the commit was merged.  Whoops! Thank-you for submitting the PR.

**Pull request closed without merging**
