### PR TITLE
libpcre2 pkg-config support

### PR DESCRIPTION
**Pull request by orlitzky**
Fix for bug 12484, the commit message explains.

### CODE REVIEW

**Comment by micahsnyder** [comment]
We've been reviewing and testing this for the last couple of days.  I found in a couple automated tests that compilation fails on freebsd when pcre2 is detected in /usr/local by pkg-config. 

Error looks like:
```
INFO     framework.utils.install_source:install_source.py:376   CC       libclamav_la-matcher-ac.lo
INFO     framework.utils.install_source:install_source.py:376 In file included from matcher-ac.c:38:
INFO     framework.utils.install_source:install_source.py:376 In file included from ./others.h:22:
INFO     framework.utils.install_source:install_source.py:376 In file included from ./matcher.h:44:
INFO     framework.utils.install_source:install_source.py:376 In file included from ./matcher-pcre.h:36:
INFO     framework.utils.install_source:install_source.py:376 ./regex_pcre.h:34:10: fatal error: 'pcre2.h' file not found
INFO     framework.utils.install_source:install_source.py:376 #include <pcre2.h>
INFO     framework.utils.install_source:install_source.py:376          ^~~~~~~~~
INFO     framework.utils.install_source:install_source.py:376 1 error generated.
INFO     framework.utils.install_source:install_source.py:376 *** Error code 1
INFO     framework.utils.install_source:install_source.py:376 
INFO     framework.utils.install_source:install_source.py:376 Stop.
```

At least I think that's where pkg-config is finding it.  One flaw of this PR is that the `pcre.m4` output doesn't show where the dependency was found so I'm guessing it was in /usr/local.

In this case, I'm seeing:

```
INFO     framework.utils.install_source:install_source.py:319 checking for X509_VERIFY_PARAM_new in -lssl... yes
INFO     framework.utils.install_source:install_source.py:319 checking for libjson installation... checking for PCRE... yes
INFO     framework.utils.install_source:install_source.py:319 configure: Compiling and linking with pcre2 from yes
...
INFO     framework.utils.install_source:install_source.py:319 configure: Summary of engine detection features
INFO     framework.utils.install_source:install_source.py:319               iconv       : yes
INFO     framework.utils.install_source:install_source.py:319               bzip2       : ok
INFO     framework.utils.install_source:install_source.py:319               zlib        : yes (from system)
INFO     framework.utils.install_source:install_source.py:319               unrar       : yes
INFO     framework.utils.install_source:install_source.py:319               preclass    : no (missing libjson-c-dev) (disabled)
INFO     framework.utils.install_source:install_source.py:319               pcre        : yes
INFO     framework.utils.install_source:install_source.py:319               libmspack   : yes (Internal)
INFO     framework.utils.install_source:install_source.py:319               libxml2     : yes, from /usr/local
INFO     framework.utils.install_source:install_source.py:319               yara        : yes
INFO     framework.utils.install_source:install_source.py:319               fts         : yes (libc)
```

Ideally it would print the path when searching for it instead of saying "`Compiling and linking with pcre2 from yes`".

I suspect the issue is that `PKG_CHECK_MODULES()` defines `PCRE_CFLAGS` but we use `PCRE_CPPFLAGS` everywhere else. Since `PCRE_CPPFLAGS` isn't generated, it would probably be easiest to globally search & replace with `PCRE_CFLAGS` to match `PKG_CHECK_MODULES()` behavior.  I'm going to mod your PR in my internal test environment and try again.

**Comment by orlitzky** [comment]
> At least I think that's where pkg-config is finding it. One flaw of this PR is that the `pcre.m4` output doesn't show where the dependency was found so I'm guessing it was in /usr/local.

You don't really know where the library is located. If it's in a non-standard location, then `PCRE_LIBS` will contain an `-L<some-path>` flag that points to it; but if it's in one of the standard paths, you don't know (and don't need to know) where it was found. Later on, linking "just works" because the library is either in the system search path, or there's any `-L` flag that puts it there.

> Ideally it would print the path when searching for it instead of saying "Compiling and linking with pcre2 from yes".

It sure would. I didn't notice that line. I was looking at the summary below it instead. We could make it say "from the system" or "from pkg-config" instead?

> I suspect the issue is that PKG_CHECK_MODULES() defines PCRE_CFLAGS but we use PCRE_CPPFLAGS everywhere else. 

Yes, that was an oversight on my part. Wherever that header file is, the FreeBSD compiler doesn't know to look there. We need to append `PCRE_CFLAGS` to `PCRE_CPPFLAGS` in the "success" branch of `PKG_CHECK_MODULES`. That looks like a semantic mismatch, but it's not.: the value of `PCRE_CFLAGS` is what `pkg-config --cflags` would output, and you can see that it contains only preprocessor flags: https://vcs.pcre.org/pcre2/code/trunk/libpcre2-8.pc.in?revision=1265&view=markup

I'm happy to amend the PR if you haven't already beat me to it.

**Comment by micahsnyder** [comment]
> > Ideally it would print the path when searching for it instead of saying "Compiling and linking with pcre2 from yes".
> 
> It sure would. I didn't notice that line. I was looking at the summary below it instead. We could make it say "from the system" or "from pkg-config" instead?

"from pkg-config" would work.  If you're up for it, doing "from pkg-config ( $PCRE_CFLAGS, $PCRE_LIBS )" would be even better so that so visual inspection can see what pkg-config provided.  I'm really fine with either though.

> I'm happy to amend the PR if you haven't already beat me to it.

I was writing up a commit message when I saw your reply.  It sounds like you have a better understanding of how the CFLAGS/CPPFLAGS change should be made.  Can you please amend the PR and then I'll put it through testing again.

**Comment by orlitzky** [comment]
Let me know if that doesn't fix things on FreeBSD, but I think it will. I can squash the commits too if you're picky about the history.

**Comment by micahsnyder** [comment]
> 
> 
> Let me know if that doesn't fix things on FreeBSD, but I think it will. I can squash the commits too if you're picky about the history.

Thanks I'll give it a try!  Don't worry about squashing, I'll handle it.

**Comment by micahsnyder** [comment]
The tests looked good now, and here's some output from manual testing on a freebsd 12.1 jail:

```
configure: Summary of detected features follows
              OS          : freebsd12.1
              pthreads    : yes (-lthr)
configure: Summary of miscellaneous features
              check       : -L/usr/local/lib -lcheck  (auto)
              fanotify    : no (disabled)
              fdpassing   : 1
              IPv6        : yes
              openssl     : /usr
              libcurl     : /usr/local
configure: Summary of optional tools
              clamdtop    : yes (-lncurses)
              milter      : no (missing libmilter) (disabled)
              clamsubmit  : yes (libjson-c-dev found at /usr/local, linking=dynamic)
              clamonacc   : no (auto)
configure: Summary of engine performance features
              release mode: yes
              llvm        : no (disabled)
              mempool     : yes
configure: Summary of engine detection features
              iconv       : yes
              bzip2       : ok
              zlib        : yes (from system)
              unrar       : yes
              preclass    : yes (libjson-c-dev found at /usr/local, linking=dynamic)
              pcre        : pkg-config ( -L/usr/local/lib -lpcre2-8  -I/usr/local/include  )
              libmspack   : yes (Internal)
              libxml2     : yes, from /usr/local
              yara        : yes
              fts         : yes (libc)
```

Will merge it momentarily.

**Comment by micahsnyder** [comment]
Merged!  Here are the commits: https://github.com/Cisco-Talos/clamav-devel/compare/a9933ef13841...f03092588b6e

**Comment by orlitzky** [comment]
Awesome, thanks.

**Pull request closed without merging**
