### PR TITLE
test(1) uses = for string equality. (== is a bashism)

### PR DESCRIPTION
**Pull request by prlw1**

### CODE REVIEW

**Comment by micah-at-talos** [comment]
Hi @prlw1 thanks for the PR. 
Is there a specific shell we should test to verify that this fixes broken behavior?

**Comment by prlw1** [comment]
Isn't it the other way around: check that your bash still works after the patch?
(Read the test(1) man page otherwise)

**Comment by prlw1** [comment]
ping? (This really is a trivial patch...)

**Comment by micahsnyder** [comment]
Sorry @prlw1 , we've just been focused on other things.  Will put in an internal copy of this pr and run it through the test suite before merging.

**Comment by micahsnyder** [comment]
We just merged an internal copy of your PR into dev/0.103.  See the commits here: 
https://github.com/Cisco-Talos/clamav-devel/compare/d5a733ef9031...54c766d1843e

@prlw1 Thanks for submitting this fix.

**Pull request closed without merging**
