### PR TITLE
Include filename in config file line reports

### PR DESCRIPTION
**Pull request by jsoref**
Not knowing the config filename is frustrating...

### CODE REVIEW

**Comment by m-sola** [comment]
This fails to compile since the cfgfile var isn't available to the optadditem function.

**Comment by micah-at-talos** [comment]
It looks to me like `optadditem()` has a definition and 2 declarations (`libfreshclam.h`, `optparser.h`), but is never actually used anywhere. 

@m-sola , do you object to removing `optadditem()` from the codebase?

**Comment by micah-at-talos** [comment]
I semi-retract my remarks.  It must exist for libfreshclam users.  I wonder if it's actually used.

**Comment by micah-at-talos** [comment]
Your approach works, @jsoref, thoug I would be happier removing `cfgfile` and `line` from `optadditem()`, honestly.  There is no file and there are no line numbers.

**Comment by micah-at-talos** [comment]
I pulled in your PR here:
https://github.com/Cisco-Talos/clamav-devel/commit/57b0a260e1d2af1b2d3b179cfe0f76f9cd12e657
And made a slight modification here:
https://github.com/Cisco-Talos/clamav-devel/commit/76d0d93d4f11a43f237cce495765b0f95d4352d1

**Pull request closed without merging**
