### PR TITLE
build: Use pkg-config to find libxml2

### PR DESCRIPTION
**Pull request by Polynomial-C**
Otherwise we get unneccesary linkage to icu and other unwanted stuff

Bug: https://bugzilla.clamav.net/show_bug.cgi?id=12202
Gentoo-bug: https://bugs.gentoo.org/661328
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>

### CODE REVIEW

**Comment by micahsnyder** [comment]
Sorry about the long delay on this.  Will look at it for inclusion in 0.103.

**Comment by micahsnyder** [comment]
@Polynomial-C It appears this change would break the build on many systems that don't have pkg-config.  I'd be more inclined to go the other way and try to adopt GNOME's official m4 files for finding dependencies like libxml2 (https://gitlab.gnome.org/GNOME/libxml2/blob/master/libxml.m4)

In local testing w/ my mac, I found that libxml2 detection with your PR (after running `autoreconf -ifv`) fails to detect a locally installed libxml2 in favor of one apparently found in /usr/local, despite using the `./configure --with-xml=<path/to/my/local/install>` option. 

Do you have a specific use case where adding pkg-config support to libxml2's m4 file fixes your build?

**Comment by chewi** [comment]
I think a compromise would be reasonable here such as using pkg-config unless a non-yes/no value is given to `--with-xml`. Overlinking causes unnecessary breakage when libraries like ICU are updated. pkg-config also helps enormously when cross-compiling and in other odd situations.

**Comment by micahsnyder** [comment]
@chewi That sounds like a good compromise to me.  I want to improve our m4 library detections but I can't break the build for downstream users on various platforms (again, heh).  

Do you or @Polynomial-C have the time to put together a new PR (or update and re-open this PR) with the described functionality?

**Comment by orlitzky** [comment]
If pkg-config is there and if libxml2 supplies a *.pc file, you might as well use it. If you want to keep support for systems without it, the entire existing check can be copy/pasted into the "fail" branch of `PKG_CHECK_MODULES` that gets run when pkg-config isn't available or there's no *.pc file for libxml2.

**Pull request closed without merging**
