### PR TITLE
pdf: do not override pdf->fileIDlen if there is no new fileID.

### PR DESCRIPTION
**Pull request by clem1**

### CODE REVIEW

**Comment by micahsnyder** [comment]
Hi @clem1 this bug-fix makes sense to me.  I am curious though - how did you encounter this issue?  It seems very specific!  

Is there a test case I can use to show fixed behavior?

**Comment by micahsnyder** [comment]
https://github.com/Cisco-Talos/clamav-devel/compare/bbbbac807986...8db3476dfed2

Merged.  Thanks again :)

Do let me know how you found the bug, if you're allowed to share.  I am quite curious.

**Comment by clem1** [comment]
Le ven. 17 juil. 2020 à 01:42, Micah Snyder <notifications@github.com> a
écrit :

> Hi @clem1 <https://github.com/clem1> this bug-fix makes sense to me. I am
> curious though - how did you encounter this issue? It seems very specific!
>
> Is there a test case I can use to show fixed behavior?
>

Hi Micah, thanks for the merge!

The issue was encountered in a real PDF which I cannot share unfortunately.
I managed to create this PDF which seems to be reproducing the issue on my
side.

**Comment by clem1** [comment]
Sorry. Here is the [pdf](https://github.com/Cisco-Talos/clamav-devel/files/4937543/bla.pdf).

**Pull request closed without merging**
