### PR TITLE
Vector register optimization using intrinsics.

### PR DESCRIPTION
**Pull request by ElliePenguins**
Character matching in cli_bm_scanbuff modified to use vector registers, specifically sse4.2

Also includes the required code to allow multiple hardware specific optimizations to be added in the future, as well as run-time hardware feature detection.

### CODE REVIEW

**Comment by micahsnyder** [comment]
Hi @ElliePenguins 

I'm seeing this build error:

```
  CC       libclamav_la-matcher-bm.lo
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:37:0,
                 from ../../../libclamav/matcher-bm.c:28:
../../../libclamav/matcher-bm.c: In function ‘charSearch_sse4_2’:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:631:1: error: inlining failed in call to always_inline ‘_mm_cmpistri’: target specific option mismatch
 _mm_cmpistri (__m128i __X, __m128i __Y, const int __M)
 ^~~~~~~~~~~~
../../../libclamav/matcher-bm.c:472:13: note: called from here
       *j += _mm_cmpistri(xbp, xpt,
             ^~~~~~~~~~~~~~~~~~~~~~
       _SIDD_UBYTE_OPS |_SIDD_CMP_EQUAL_EACH | _SIDD_NEGATIVE_POLARITY);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:37:0,
                 from ../../../libclamav/matcher-bm.c:28:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:631:1: error: inlining failed in call to always_inline ‘_mm_cmpistri’: target specific option mismatch
 _mm_cmpistri (__m128i __X, __m128i __Y, const int __M)
 ^~~~~~~~~~~~
../../../libclamav/matcher-bm.c:472:13: note: called from here
       *j += _mm_cmpistri(xbp, xpt,
             ^~~~~~~~~~~~~~~~~~~~~~
       _SIDD_UBYTE_OPS |_SIDD_CMP_EQUAL_EACH | _SIDD_NEGATIVE_POLARITY);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:37:0,
                 from ../../../libclamav/matcher-bm.c:28:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:631:1: error: inlining failed in call to always_inline ‘_mm_cmpistri’: target specific option mismatch
 _mm_cmpistri (__m128i __X, __m128i __Y, const int __M)
 ^~~~~~~~~~~~
../../../libclamav/matcher-bm.c:480:20: note: called from here
        uint8_t y = _mm_cmpistri(xbp, xpt,
                    ^~~~~~~~~~~~~~~~~~~~~~
      _SIDD_UBYTE_OPS |_SIDD_CMP_EQUAL_EACH | _SIDD_NEGATIVE_POLARITY);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:37:0,
                 from ../../../libclamav/matcher-bm.c:28:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:631:1: error: inlining failed in call to always_inline ‘_mm_cmpistri’: target specific option mismatch
 _mm_cmpistri (__m128i __X, __m128i __Y, const int __M)
 ^~~~~~~~~~~~
../../../libclamav/matcher-bm.c:480:20: note: called from here
        uint8_t y = _mm_cmpistri(xbp, xpt,
                    ^~~~~~~~~~~~~~~~~~~~~~
      _SIDD_UBYTE_OPS |_SIDD_CMP_EQUAL_EACH | _SIDD_NEGATIVE_POLARITY);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:1938: recipe for target 'libclamav_la-matcher-bm.lo' failed
make[5]: *** [libclamav_la-matcher-bm.lo] Error 1
make[5]: Leaving directory '/home/build/jenkins/workspace/test-pipelines_build-0.103/clamav-0.103.0-devel-20200430/_build/sub/libclamav'
Makefile:4336: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/build/jenkins/workspace/test-pipelines_build-0.103/clamav-0.103.0-devel-20200430/_build/sub/libclamav'
Makefile:1463: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/build/jenkins/workspace/test-pipelines_build-0.103/clamav-0.103.0-devel-20200430/_build/sub/libclamav'
Makefile:853: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/build/jenkins/workspace/test-pipelines_build-0.103/clamav-0.103.0-devel-20200430/_build/sub'
Makefile:649: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/build/jenkins/workspace/test-pipelines_build-0.103/clamav-0.103.0-devel-20200430/_build/sub'
Makefile:1061: recipe for target 'distcheck' failed
make: *** [distcheck] Error 1
```

**Comment by ElliePenguins** [comment]
Hello @micahsnyder 
I think this should work:

CFLAGS='-msse4.2' ./configure

**Comment by micahsnyder** [comment]
Hi @ElliePenguins I wanted to respond just so you know where my head is at with regards to your patch.  I'm very curious to know what sort of performance improvement we'd see with this change.  If you have any examples that highlight the improvement from this optimization I would really appreciate it.  

I also hope to play with this a bit, but given that it's not production ready and has build issues and compatibility issues with other platforms, it's likely going to be a while before I or one of my team members finds any time to play around with it and test it enough to understand the benefit of including the change.  

Even if we do find that there's an improvement in scan performance with this, we'll probably ask if you can help make the build with this change work for all supported platforms.

Regards,
Micah

**Comment by ElliePenguins** [comment]
Hello @micahsnyder, this code patch was originally created as a project for a software optimization class, because of this all of the development notes are available at: [project](https://penguins879376500.wordpress.com/category/school-work/project/)

Currently, this optimization seems to provide ~2-3% speed up. My thoughts however are that the included scaffolding would allow the implementation of other hardware specific code, for example, AVX, NEON, and specifically SVE; which I am hopeful would provide much more of an improvement.

This has been an enjoyable project to work on, so if there is interest in this, I would of course like to continue to help with it.

Cheers,
ElliePenguins

**Comment by micahsnyder** [comment]
Hi @ElliePenguins sorry I haven't had time to play with this yet! We're still very distracted with other things at present

**Comment by micahsnyder** [comment]
I've come to realize that we won't have time to productize this work, or fully test it without some assistance.

@ElliePenguins do you have write-up with benchmarking methods and results?

To make it more likely that we could integrate your work - we would really need sse4.2 detection/support added to the build systems so that this feature is exercised when available and doesn't break the build when not available.  Would you be able to complete this the productization and provide your benchmark research for review?

**Comment by ElliePenguins** [comment]
Hello @micahsnyder,
I would like to continue on this and will start working on the build system.

These blog posts provide some detail of the build options and run times; however, I feel a new post summarizing this information may be more helpful and will try to get that together as well:  

- [benchmark](https://penguins879376500.wordpress.com/2019/11/15/project-update/)  
- [results](https://penguins879376500.wordpress.com/2019/11/24/project-progress-update/)  

I also think I should mention not to feel rushed, I will try to document the continued development along the way so it can be handled when it is more appropriate for yourself and team.

**Comment by micahsnyder** [comment]
I keep reviewing this and thinking about it.  The test data referenced in https://penguins879376500.wordpress.com/2019/11/10/main-project-benchmark/ seems like a reasonable way to do the tests.  Can I assume it's using a static copy of the standard databases?  The performance varies dramatically based on signature database content.
 
I have heard that `-O3` with Clang performs some vectorizing optimizations, though I have no expertise to know how it compares.

It is fascinating research though I don't think a 3% warrants the added complexity to the project.  If you end up with better optimization rules, it would be worth reconsidering, but for now I think we may be best off declining this change.

**Comment by ElliePenguins** [comment]
That is understandable. The copy of the databases was downloaded with freshclam and resides in installed/share/clamav.

I believe that adding a -O2 or -O3 would enable autovectorization, and as I understand it is a better option in regards to simplicity and portability. The use of intrinisics was because this block would not autovectorize even with modification.
Unfortunately, I agree it became more complicated then originally hoped.

Thank you for your feedback, it was an excellent learning experience that maybe I'll be able to revisit.

**Comment by micahsnyder** [comment]
Thanks for your understanding @ElliePenguins
Keep learning and having fun!

**Pull request closed without merging**
